{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox.fullname" . }}
  labels:
{{ include "netbox.labels" . | indent 4 }}
type: Opaque
data:
  {{ if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecretName) -}}
  db_password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{ end -}}
  email_password: {{ .Values.email.password | b64enc | quote }}
  napalm_password: {{ .Values.napalm.password | b64enc | quote }}
  {{ if and (not .Values.redis.enabled) (not .Values.externalRedis.existingSecretName) -}}
  redis_password: {{ .Values.externalRedis.password | b64enc | quote }}
  {{ end -}}
  secret_key: {{ .Values.secretKey | default (randAscii 60) | b64enc }}
  superuser_password: {{ .Values.superuser.password | default (randAlphaNum 16) | b64enc }}
  superuser_api_token: {{ .Values.superuser.apiToken | default uuidv4 | b64enc }}
{{- end -}}
